# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Site settings for your sports blog
title: "La Fiera Deportiva"
subtitle: "Passionate Sports Coverage"
name: "Hernan Espinoza Jr."
description: "A passionate sports blog covering latest news and analysis."
url: "https://lafieradeportiva.com"
# locale: "es"  # For Spanish

# Add to _config.yml
minimal_mistakes_skin: "neon"# Options: default, air, contrast, dark, dirt, mint, sunrise, aqua, neon, plum

# Navigation
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Pages
- scope:
    path: ""
    type: pages
  values:
    layout: single
    author_profile: fales

# Match reports
- scope:
    path: "_posts"
    type: posts
  values:
    layout: match_reports
    categories: [soccer]

# Include additional dirs
include:
  - _pages

# Main navigation links
main:
  - title: "Home"
    url: /
  - title: "Soccer"
    url: /soccer/
  - title: "Basketball"
    url: /basketball/
  - title: "Scoreboard"
    url: /scoreboard/
  - title: "About"
    url: /about/

author:
  name: "Sports Analyst"
  bio: "Passionate sports journalist with over 5 years covering major leagues."
  location: "Chicago, Illinois"
  links:
    - label: "X"
      icon: "fab fa-fw fa-twitter-square"
url: "https://x.com/hernanespn"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/lafieradeportiva/?hl=en"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/user/hernancitohesjr"

footer:
  links:
    - label: "X"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/hernanespn"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/lafieradeportiva/?hl=en"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/user/hernancitohesjr"


